### ISSUE TITLE
v0.7.6 Initial sync job failing with Value was either too large or too small for an Int16.

### ISSUE THREAD

**Issue by kskilling** [orangeglasses/vROAST#18] opened 2019-04-03 09:09 UTC
Redeployed with v7.0.6 based on resolution to issue #17 .
Sync job is now failing in vROAST (so that part of the resolution has worked) and not pushing any content to git repo (which I emptied before redeploying the ova).

Error from most recent run of the job is:
Failure during jobexecution
+4m 17.288sError! Value was either too large or too small for an Int16.
+4m 17.301sStacktrace:    at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToInt16(String value, Int32 fromBase)
   at MedKit.Xml.UnicodeHelper.decodeString(String source) in /app/Common/Xml/UnicodeHelper.cs:line 61
   at MedKit.Convert.ActionType..ctor(XmlDocument actionXml, String context) in /app/Common/Convert/ActionType.cs:line 78
   at MedKit.Convert.Converter.ActionsToTS() in /app/Common/Convert/Converter.cs:line 165
   at MedKit.Jobs.JobExecuter.executePullFromVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 212
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 102
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 55

I will provide a complete log file via email.

**Comment by floreseken** [comment] 2019-04-05 10:43
Okay, this is caused by some unexpected content in the code part of an action in your setup. But unfortunately with the current logging we are not able to tell which one.

So, I made a new version which allows us to see which action exactly it is failing on. Could you please try again with that version?

**Comment by kskilling** [comment] 2019-04-05 17:29
0.7.7 deployed, I will send across the log file via email but it shows the action on which it is failing as one provided by the Puppet plugin. The action is named YAMLParser, I've upload a copy of it to my Git repo so you should be able to access it from there if you don't already have a copy in your vRO environment.

**Comment by floreseken** [comment] 2019-04-09 10:45
Ok. Interesting. This appears to be a encoded script or something. What do you see when you open this action in the editor? I see this when extracting the file from it:

![image](https://user-images.githubusercontent.com/6927344/55794337-44276380-5ac5-11e9-9ef4-6fb798a28932.png)

Do you see actual code?

**Comment by kskilling** [comment] 2019-04-09 13:06
How are you opening the action? It's not being synched to the Git repo and it doesn't open directly from the exported file in VSCode. Are you getting the action file from somewhere else?

**Comment by floreseken** [comment] 2019-04-09 13:11
The actionfile is actually a zip, so you can unzip it and it contains an action-content file.. that is the one you see above. 

But I'll bet if you do that, you will see the same..

What I meant was via the vRO client.. what do you see there?

**Comment by kskilling** [comment] 2019-04-09 14:40
Understood. If I unzip the exported action and open the action-content file in VSCode I see the same as your screenshot as you predicted. 

In the vRO client I can see the contents of the action without issue, it's got one enormous line of code, but I can copy and paste it out to wrap the lines to view it more clearly in notepad++ for example. There's too much code in that one line to really spot if there is anything strange hidden in the code.

**Comment by floreseken** [comment] 2019-04-10 07:54
Check. I now have the action restored on my system and see the same. I should be able to debug this now.

**Comment by floreseken** [comment] 2019-04-10 08:00
So, this is what you see in a 'normal' action..

![image](https://user-images.githubusercontent.com/6927344/55861671-21558780-5b77-11e9-8463-68cc4b7f4e33.png)

your yamlparser somehow has some sort of encoding. Not sure where this comes from, in the UI I cannot find a 'encode' button or something. We first need to find out what sort of encoding this is...

**Comment by floreseken** [comment] 2019-04-10 08:49
I'm a bit further... whether or not the encoding happens depends on the code content. For instance if the code contains ]]> it will be encoded. The YamlParser does not contain this... so there are more.. I need to find out which ones.

The 'encoding' is converting every char to their ASCII hex version in four digits. So this code:

]]>

Will translate to:

![image](https://user-images.githubusercontent.com/6927344/55865194-2b2eb900-5b7e-11e9-9835-e43c6f9fad51.png)

005d = ]
00e3 = >

**Comment by floreseken** [comment] 2019-04-10 13:32
OK! this is fixed in the new release.

https://github.com/orangeglasses/vROAST/releases/tag/0.7.8

**Closed as completed by floreseken** 2019-04-10 13:32 UTC
