### ISSUE TITLE
Job showing as Succeeded but failing to push into vRO

### ISSUE THREAD

**Issue by ymmit85** [orangeglasses/vROAST#17] opened 2019-04-01 07:38 UTC
+3.734sNow pushing converted vRO content
+3.740sFailure during jobexecution
+3.745sError! Connection refused Connection refused
+3.755sInner exception: Connection refused
+3.764sStacktrace:    at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at MedKit.vRO.vROClient.getAllCategories(WebClient web, String type, Boolean isRoot) in /app/Common/vRO/vROClient.cs:line 589
   at MedKit.vRO.vROClient.getExistingCategories(WebClient web, String type, Boolean isRoot) in /app/Common/vRO/vROClient.cs:line 569
   at MedKit.vRO.vROClient.PutContent(String type, List`1 onlyIncludeFiles) in /app/Common/vRO/vROClient.cs:line 337
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 117
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 42

**Comment by floreseken** [comment] 2019-04-01 08:12
Can you share more of your logfile? Maybe by mail: feken@itq.nl 

I'm missing a bit of context without all previous logging.

**Comment by floreseken** [comment] 2019-04-01 11:15
Based on the logs you sent me. vROAST is having lots of troubles connecting to vRO.
What do you see when you open this in a browser?

https://[your vRO server]/vco/api

Thanks

**Comment by ymmit85** [comment] 2019-04-01 12:32
Can see the API, also browse to links within and authenticate.
Which API URL is it trying to access at the point it's failing at?

**Comment by kskilling** [comment] 2019-04-01 17:06
I'm getting the same issue with v0.7.5.
In my case the initial sync job has only uploaded a portion of my vRO inventory to github. I can see plenty of the out of the box modules but most of my custom action modules are missing, even where they don't have a com.vmware.* naming format. I've left it for a few hours but it hasn't resolved itself.

The log file has similar error messages to those reported by @ymmit85 although slightly different line numbers. 

Then as a test I created a basic new action (in a new module folder which does not contain com.vmware in the name) in VSCode and pushed it to my repo. It's accessible within Git but hasn't been sync'd down to vRO. Looking at jobs dashboard I see the same connection refused error messages. 

I can email log file if required.

**Comment by floreseken** [comment] 2019-04-02 07:31
The 'Job showing as Succeeded but failing' part will be covered by 0.7.6.

**Comment by floreseken** [comment] 2019-04-02 08:13
Okay, I have a lead on the other problem. The log of Tim still shows evidence of the of the same jobs executing simultaneously:

![image](https://user-images.githubusercontent.com/6927344/55386380-a7e2e700-552f-11e9-8ccc-8474a9fc7541.png)

The encircled numbers are thread numbers. 
The last release should have prevented this.. The change made it better but apparently did not fix it completely.

**Comment by floreseken** [comment] 2019-04-02 12:29
So this turns out be be the same problem as #13 but our fix in 0.7.5 depending on hangfire did not fix this. Version 0.7.6 contains a new fix which should work better.

The problem is hard to reproduce for us since is seems to be caused the speed of the configured vRO server. 0.7.6 should do a better job.

**Comment by floreseken** [comment] 2019-04-02 12:30
Please open a new issue if the problem persists. I'm closing this one.

**Closed as completed by floreseken** 2019-04-02 12:30 UTC
